# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ba8a85f5f98464fc1ca3c2b7f2eae6272e5db525a12e7578d977ed30ef09cc76cd15728feaa8d221e09e50a96c832ac84ff3cf2b8b2390587ba5d09f42a954

test:
  secret_key_base: 64ee51d8417eebc43fff3667c8bcfc64dd747d4a03b17efd5acaef96d4e710dabb907f4110b66a7a117875064571d96c09738c5d8507d22d9e9bea1a66fbf31a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
